name: Weather forecast and analysis sending

on:
  schedule:
    # Запуск в 4:00 UTC (6:00 по Киеву)
    - cron: '0 4 * * *'

  # Позволяет запускать скрипт вручную во вкладке Actions
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip' # Кэширование зависимостей для ускорения запусков

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Weather Script
        # Здесь мы прокидываем секреты из настроек GitHub в переменные окружения
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python OWM_send_data.py